# Generated by Django 3.0.8 on 2020-07-08 19:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='DOB',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='Gender',
        ),
    ]
